imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: thumbnails.yml }
    - { resource: doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
      save_path:            %kernel.cache_dir%/../sessions

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
      resources:
       - "RodgermdSfToolsBundle:Form:fields.html.twig"

# Assetic Configuration

parameters:
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.http_path:  /images
    languages:
      en: English
      es: Spanish

stfalcon_tinymce:
  tinymce_jquery: true

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [SonataAdminBundle, SiteBaseBundle]
    #java: /usr/bin/java
    filters:
      sass:    ~
      compass: ~
      yui_css:
        jar: %yui_compressor%
      yui_js:
        jar: %yui_compressor%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

vich_uploader:
    db_driver: orm

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Site\UserBundle\Entity\User

sonata_admin:
  title: Project 21 May Administration

sonata_doctrine_orm_admin:
  entity_manager: ~

sonata_block:
  default_contexts: [cms]
  blocks:
    sonata.admin.block.admin_list:
      contexts:   [admin]

stof_doctrine_extensions:
  orm:
    default:
      timestampable: true
      sluggable: true
      translatable: true

personal_translations_widget:
  languages: %languages%

site_base:
  emails:
    from: 21demayo@turismo21demayo.cl
    to: 21demayo@turismo21demayo.cl

