parameters:
    database_name:     symfony
    database_user:     root
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    dev_mailer_transport:  gmail
    dev_mailer_user:       ~
    dev_mailer_password:   ~

