jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Site\UserBundle\Entity\User:
          algorithm:           sha512
          encode_as_base64:    true
          iterations:          115

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      fos_userbundle:
        id: fos_user.user_manager

    encoders:
      Site\UserBundle\Entity\User: sha512

    firewalls:
      main:
        pattern: ^/
        form_login:
            provider: fos_userbundle
            csrf_provider: form.csrf_provider
            check_path: /user/login_check
            login_path: /user/login
            use_referer: true
        logout:       true
        anonymous:    true
        remember_me:
          key:      %secret%
          lifetime: 604800
          path:     /
          domain:   ~


    access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }
