services:
  uploader.namer.md5:
    class: Site\BaseBundle\Namer\MD5FileNamer

  liip_imagine.data.loader.stream.accommodation:
    class: "%liip_imagine.data.loader.stream.class%"
    arguments:
      - "@liip_imagine"
      - 'gaufrette://accommodation_fs/'
    tags:
      - { name: 'liip_imagine.data.loader', loader: 'stream.accommodation' }

  liip_imagine.data.loader.stream.route:
    class: "%liip_imagine.data.loader.stream.class%"
    arguments:
      - "@liip_imagine"
      - 'gaufrette://route_fs/'
    tags:
      - { name: 'liip_imagine.data.loader', loader: 'stream.route' }


knp_gaufrette:
  stream_wrapper: ~
  adapters:
    accommodation:
      local:
        directory: %kernel.root_dir%/../web/uploads/accomodation
    route:
      local:
        directory: %kernel.root_dir%/../web/uploads/route

  filesystems:
    accommodation_fs:
      adapter:    accommodation
    route_fs:
      adapter:    route

vich_uploader:
  db_driver: orm
  gaufrette: true
  storage: vich_uploader.storage.gaufrette
  mappings:
    accommodation:
      uri_prefix: /
      upload_destination: accommodation_fs
      namer: uploader.namer.md5
    route:
      uri_prefix: /
      upload_destination: route_fs
      namer: uploader.namer.md5

liip_imagine:
  driver: imagick

  filter_sets:

  ################
  # ACCOMMODATIONS
  ################

    accomodation_small:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [40, 40], mode: outbound }
    accommodation_admin_preview:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [150, 150], mode: outbound }
    admin_image_small:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [50, 50], mode: outbound }

    accommodation_menu_dropdown:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [255, 92], mode: outbound }

    selected_for_homepage:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [375, 137], mode: outbound }
    accommodations_list:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [425, 155], mode: outbound }
    accommodation_big:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [745, 252], mode: outbound }
    accommodation_maximum:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [2000, 2000], mode: inbound }
    accommodation_images_list:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [120, 120], mode: outbound }
    accommodation_sticky:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [150, 150], mode: outbound }


  ################
  # ROUTES
  ################

    route_image_small:
      data_loader: stream.route
      filters:
        thumbnail: { size: [50, 50], mode: outbound }
    route_menu_dropdown:
      data_loader: stream.route
      filters:
        thumbnail: { size: [255, 92], mode: outbound }
    route_admin_preview:
      data_loader: stream.route
      filters:
        thumbnail: { size: [150, 150], mode: outbound }

    route_maximum:
      data_loader: stream.route
      filters:
        thumbnail: { size: [2000, 2000], mode: inbound }
    route_images_list:
      data_loader: stream.route
      filters:
        thumbnail: { size: [120, 120], mode: outbound }

    route_sticky:
      data_loader: stream.route
      filters:
        thumbnail: { size: [150, 150], mode: outbound }

    routes_list:
      data_loader: stream.route
      filters:
        thumbnail: { size: [425, 155], mode: outbound }

