services:
  uploader.namer.md5:
    class: Site\BaseBundle\Namer\MD5FileNamer

  liip_imagine.data.loader.stream.accommodation:
          class: "%liip_imagine.data.loader.stream.class%"
          arguments:
              - "@liip_imagine"
              - 'gaufrette://accommodation_fs/'
          tags:
              - { name: 'liip_imagine.data.loader', loader: 'stream.accommodation' }

knp_gaufrette:
  stream_wrapper: ~
  adapters:
    accommodation:
      local:
        directory: %kernel.root_dir%/../web/uploads/accomodation

  filesystems:
    accommodation_fs:
      adapter:    accommodation

vich_uploader:
  db_driver: orm
  gaufrette: true
  storage: vich_uploader.storage.gaufrette
  mappings:
    accommodation:
      uri_prefix: /
      upload_destination: accommodation_fs
      namer: uploader.namer.md5

liip_imagine:
  driver: imagick

  filter_sets:
    accomodation_small:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [40, 40], mode: outbound }
    accommodation_admin_preview:
      data_loader: stream.accommodation
      filters:
        thumbnail: { size: [150, 150], mode: outbound }
