knp_gaufrette:
  adapters:
    accommodation:
      local:
        directory: %kernel.root_dir%/../images/accomodation

  filesystems:
    accommodation_fs:
      adapter:    accommodation

vich_uploader:
  db_driver: orm
  gaufrette: true
  storage: vich_uploader.storage.gaufrette
  mappings:
    accommodation:
      upload_destination: accommodation_fs
      namer: my.namer.product

liip_imagine:
  driver: imagick
  filter_sets:
    small:
      filters:
        thumbnail: { size: [40, 40], mode: outbound }