services:
  site.twig.helper.image:
    class: Site\BaseBundle\Twig\ImageHelper
    arguments: [@service_container, @liip_imagine.twig.extension]
    tags:
    - { name: twig.extension }

  site.languages_getter:
    class: Site\BaseBundle\Languages\LanguagesGetter
    arguments: [%languages%]
    tags: [{ name: languages_getter }]