<?php

namespace Site\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccommodationRepository extends EntityRepository
{
  /**
   * Gets sorted accommodations
   * @return array
   */
  public function getSorted()
  {
    return $this->createQueryBuilder('a')->orderBy('a.title', 'asc')->getQuery()->getResult();
  }
}

